### ISSUE TITLE
ModDB Manual Download Issue

### ISSUE THREAD

**Issue by SentaiBrad** [TheMrNewVegas/dnd#1]
I got to the Manual Download portion of the Installer, and it refuses to proceed. I loaded up Edge outside of Wabbajack and made sure ModDB had all the permissions needed, and It will always refuse to download. I copied the URL and downloaded it manually in firefox, and put it inside my Oblivion D&D Downloads folder. However, Wabbajack does not check its hash and still asks me to download it manually.

Is there another workaround I can try, is it Wabbajack, or the installer? I tried the installer on Wabbajack 3.0.1.9 and 3.0.3.1.

Edit: Ah, ok. So, Wabbajack IS hashing the downloads from a separate browser, but there are multiples and if you close the browser window that Wabbajack opens up it doesn't continue. It adds several steps each time. Don't know if its fixable.

**Comment by russellleesmith** [comment]
Did you ever get this installed? I'm following the steps, but the first file download attempt sends me to a manual download page. When I attempt to download that file, Wabbajack crashes.

**Comment by russellleesmith** [comment]
I answered my own question with the FAQ: https://github.com/TheMrNewVegas/dnd/wiki/FAQ
